version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - pg
    depends_on:
      - pg
  pg:
    image: bitnami/postgresql:11-debian-9
    container_name: pg
    environment:
      POSTGRESQL_USERNAME: kiama
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: kiama-network
    ports:
      - '5432:5432'
    networks:
      - backend
  rabitmq:
    image: bitnami/rabbitmq:3-management-alpine
    container_name: rabitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backend
    restart: 'unless-stopped'
    depends_on:
      - proxy
    links:
      - proxy
  auth:
    container_name: auth-management
    build: ./auth
    dockerfile: Dockerfile
    ports:
      - '3001:3000'
    environment:
      - PORT=3000
      - AMP_URL=amqp://localhost:5672
      - DATABASE_URL= postgresql://kiama:password@localhost:5432/kiama-network
      - SECRET_KEY = secretKey
      - LOG_FORMAT = dev
      - LOG_DIR = ../logs
      - ORIGIN = *
      - CREDENTIALS = true

    links:
      - rabbitmq

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
